version: "3.7"
services:
  postgres:
    image: postgres:16.1
    container_name: postgresdb
    # Make postgres logs. More information about logging, see official documentation: https://www.postgresql.org/docs/11/runtime-config-logging.html
    command: postgres -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on
    logging:
      options:
        max-size: "10k"
        max-file: "5"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sdmt
      POSTGRES_INIT_DB_ARGS: "--encoding=UTF-8"
    volumes:
      - ./postgres/initdb:/docker-entrypoint-initdb.d
